### ISSUE TITLE
adding cache buster

### ISSUE THREAD

**Issue by ernscht** [namics/nitro-exporter#3]
Adding a cache buster would be a nice addition to the exporter.
Using a revision hash in static assets is the best solution to the caching problem.
[gulp-rev](https://www.npmjs.com/package/gulp-rev) seems to be a good choice to start.
There are also many gulp-rev extensions.
What do you think?

**Comment by jantimon** [comment]
Just a side node for newer projects - webpack can add thoses hashes out of the box

**Comment by ernscht** [comment]
Development moved to [Nitro generator monorepo](https://github.com/namics/generator-nitro)
